# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_best_type_double <- function(values) {
    .Call(`_chihaya_get_best_type_double`, values)
}

get_best_type_int <- function(values) {
    .Call(`_chihaya_get_best_type_int`, values)
}

h5exists <- function(path, host, name) {
    .Call(`_chihaya_h5exists`, path, host, name)
}

validate_ <- function(path, name) {
    .Call(`_chihaya_validate_`, path, name)
}

write_integer_scalar <- function(path, host, name, val) {
    .Call(`_chihaya_write_integer_scalar`, path, host, name, val)
}

write_double_scalar <- function(path, host, name, val) {
    .Call(`_chihaya_write_double_scalar`, path, host, name, val)
}

write_string_scalar <- function(path, host, name, val) {
    .Call(`_chihaya_write_string_scalar`, path, host, name, val)
}

